### PR TITLE
React Beautiful DND v. 12.0.0 

### PR DESCRIPTION
**Pull request by kayluhb**
Add support for React Beautiful DND v. 12.0.0  https://github.com/atlassian/react-beautiful-dnd/releases/tag/v12.0.0

```
For most people: you can safely upgrade to 12.0! 🎉 If you are doing any of the following then you will need to change some things. This is just a super quick reference to see if you can upgrade safely.

We have renamed our data-* attributes. So if you were using them (perhaps in a test), then things will break for you
```

This appears to fix it in my tests, but it would be good to add some tests around this...

### CODE REVIEW

**Comment by colinrcummings** [comment]
I released this change as `next` (3.0.0-rc-0). I've installed it along with `react-beautiful-dnd` v12.0.0 in`react-beautiful-dnd-test-utils-example`, but the tests don't pass. I'm looking at it. I agree with you on the tests; co-locating the two repos would help...

**Comment by colinrcummings** [comment]
My bad; I forgot to build the `dist` before publishing. 🤦See v3.0.0-rc-1. My only suggestion would be to use the data attributes for lookups vs. those used for shared global styles:

DroppableProps: 
```
  // used for shared global styles
'data-rbd-droppable-context-id': ContextId,
// Used to lookup
 'data-rbd-droppable-id': DroppableId,
```

DraggableProps:
```
// used for shared global styles
'data-rbd-draggable-context-id': string,
// used for lookups
'data-rbd-draggable-id': string,
```
Thanks again for contributing!

**Comment by kayluhb** [comment]
Good callout.  Updated with the change.

**Comment by colinrcummings** [comment]
Released v3.0.0. 🚢

**Pull request merged**
